version: "3.8"
services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: example-root-pw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloudpw
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud:stable
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloudpw
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_TRUSTED_DOMAINS: localhost:8080
      NEXTCLOUD_OVERWRITEHOST: localhost:8080
      NEXTCLOUD_OVERWRITEPROTOCOL: http
      NEXTCLOUD_BASE: http://localhost:8080/remote.php/dav/files/admin/
      NEXTCLOUD_USER: admin
      NEXTCLOUD_APP_PASSWORD: PdYXt-3di5x-Dazkb-iJJrt-DewBd
    depends_on:
      - db
    volumes:
      - nextcloud_data:/var/www/html
    expose:
      - "80"

  proxy:
    image: nginx:stable
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db_data:
  nextcloud_data:
